### ISSUE TITLE
Upgrade to Pandas 0.20.2 causes error in df.join

### ISSUE THREAD

**Issue by SimonChristopherCropper** [GFA-RDIP/CSV_CTS#1]
Error throuwn after upgrade of pandas. Program has the following error.

Traceback (most recent call last):
  File "report.py", line 304, in <module>
    cli()
  File "report.py", line 243, in cli
    df['delta'] = (df.index.map(lambda x: x[1]) - df['date_one'])
  File "C:\Users\simon\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pandas\core\ops.py", line 702, in wrapper
    converted = _Op.get_op(left, right, name, na_op)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pandas\core\ops.py", line 334, in get_op
    return _TimeOp(left, right, name, na_op)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pandas\core\ops.py", line 372, in __init__
    rvalues)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pandas\core\ops.py", line 513, in _convert_for_datetime
    mask = isnull(lvalues) | isnull(rvalues)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pandas\core\ops.py", line 915, in wrapper
    self, other = _align_method_SERIES(self, other, align_asobject=True)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pandas\core\ops.py", line 629, in _align_method_SERIES
    left, right = left.align(right, copy=False)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pandas\core\series.py", line 2411, in align
    broadcast_axis=broadcast_axis)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pandas\core\generic.py", line 4937, in align
    fill_axis=fill_axis)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pandas\core\generic.py", line 5006, in _align_series
    return_indexers=True)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pandas\core\indexes\base.py", line 2996, in join
    return_indexers=return_indexers)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pandas\core\indexes\base.py", line 3091, in _join_multi
    raise ValueError("cannot join with no level specified and no "
ValueError: cannot join with no level specified and no overlapping names

**Comment by EdwardJRoss** [comment]
The index for the index column needed to be specified. This should be resolved on master now.
